const Teams = [
    { label: 'Atlanta Hawks'},
    { label: 'Boston Celtics'},
    { label: 'Brooklyn Nets'},
    { label: 'Charlotte Hornets'},
    { label: 'Chicago Bulls'},
    { label: 'Cleveland Cavaliers'},
    { label: 'Dallas Mavericks'},
    { label: 'Denver Nuggets'},
    { label: 'Detroit Pistons'},
    { label: 'Golden State Warriors'},
    { label: 'Houston Rockets'},
    { label: 'Indiana Pacers'},
    { label: 'Los Angeles Clippers'},
    { label: 'Los Angeles Lakers'},
    { label: 'Memphis Grizzlies'},
    { label: 'Miami Heat'},
    { label: 'Milwaukee Bucks'},
    { label: 'Minnesota Timberwolves'},
    { label: 'New Orleans Pelicans'},
    { label: 'New York Knicks'},
    { label: 'Oklahoma City Thunder'},
    { label: 'Orlando Magic'},
    { label: 'Philadelphia 76ers'},
    { label: 'Phoenix Suns'},
    { label: 'Portland Trail Blazers'},
    { label: 'Sacramento Kings'},
    { label: 'San Antonio Spurs'},
    { label: 'Toronto Raptors'},
    { label: 'Utah Jazz'},
    { label: 'Washington Wizards'}
];

export default Teams;